# Generated by Django 5.2.6 on 2025-09-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appctv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachorro',
            old_name='instagran',
            new_name='instagram',
        ),
    ]
